remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: Pilvipalvelut web-kehityksessä DIG001AS3A-3003
description: Sivustolta löydät Kasper Nurminen tehtävät liittyen Haaga-Helian kurssiin Pilvipalvelut web-kehityksessä!
